scene_name: south_building
dataset_name: south-building
image_dir: data/scenes/south_building/images
feature_dir: data/scenes/south_building/features
match_dir: data/scenes/south_building/matches
verified_dir: data/scenes/south_building/verified
track_dir: data/scenes/south_building/tracks
sparse_dir: data/scenes/south_building/sparse/0
undistorted_dir: data/scenes/south_building/undistorted
output_dir: outputs/south_building
subset:
  enabled: false
